services:
    Symfony\Component\Ldap\Ldap:
        arguments: ['@Symfony\Component\Ldap\Adapter\ExtLdap\Adapter']
        autowire: true
        autoconfigure: true
        tags:
            - ldap
    Symfony\Component\Ldap\Adapter\ExtLdap\Adapter:
        arguments:
            -   host: "localhost"
                port: 389
                # encryption: tls
                options:
                    protocol_version: 3
                    referrals: false